#pragma once

enum animation_id {
	ENTITY_PLAYER_MOVE_IDLE = 0,
	ENTITY_PLAYER_MOVE_UP,
	ENTITY_PLAYER_MOVE_LEFT,
	ENTITY_PLAYER_MOVE_DONW,
	ENTITY_PLAYER_MOVE_RIGHT,


	ENTITY_PLAYER_ATTACK_1 = 100,
	ENTITY_PLAYER_ATTACK_2, //this works?

};

