#pragma once

enum tile_id {
	FLOWER = 1,
	GRASS,
	COBBLESTONE_1,
	COBBLESTONE_2,
	COBBLESTONE_3,
	COBBLESTONE_4,
	COBBLESTONE_5,
	OUTERCORNER_TOPRIGHT,
	OUTERCORNER_TOPLEFT,
	BRICKCORNER_TOPRIGHT,
	OUTERCORNER_BOTTOMLEFT,
	OUTERCORNER_BOTTOMRIGHT,
	BRICKCORNER_TOPLEFT,
	SLANTBRICK_RIGHT,
	SLANTBRICK_TOP,
	BRICK_THICKTOP,
	SLANTBRICK_LEFT,
	SLANTBRICK_BOTTOM,
	COBBLESTONE_6,
	COBBLESTONE_7,
	COBBLESTONE_8,
};

